### ISSUE TITLE
'string index out of range' with xacro macro param line breaks

### ISSUE THREAD

**Issue by lucasw** [ros/xacro#120]
Adding a linebreak within the xacro macro params quotes produces a 'string index out of range' error in the jade and latest version of xacro.  In hydro this worked fine.

This no longer works:

```
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

<xacro:macro name="all_cameras" params="
  test
  ">
</xacro:macro>

<xacro:all_cameras test="0.5" />

</robot>
```

While this works:

```
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

<xacro:macro name="all_cameras" params="test">
</xacro:macro>

<xacro:all_cameras test="0.5" />

</robot>
```

https://github.com/lucasw/testbot/blob/master/testbot_description/urdf/param_test_linebreak.xacro
https://github.com/lucasw/testbot/blob/master/testbot_description/urdf/param_test_no_linebreak.xacro

http://answers.ros.org/question/219698/jade-xacro-macro-param-line-breaks-string-index-out-of-range/

**Comment by rhaschke** [comment]
@codebot I will have a look.
