### ISSUE TITLE
Warning: xacro.cmake being included automatically

### ISSUE THREAD

**Issue by danepowell** [ros/xacro#13]
When building a package depending on xacro, I get the following warning:

```
[rosbuild] WARNING: the file /opt/ros/groovy/stacks/xacro/cmake/xacro.cmake is being included automatically...
```

I found [trac ticket #4792](https://code.ros.org/trac/ros-pkg/ticket/4792) about this issue that was never closed. I think the solution could be as simple as changing manifext.xml to use

```
<export>
  <rosbuild cmake_directory="${prefix}/cmake"/>
</export>
```

Oddly, even if I do that, and include rosbuild_include(xacro xacro) in my CMakeLists, I still get the warning. I don't know why that is.

**Comment by wjwwood** [comment]
What version of ROS is this? fuerte?

**Comment by wjwwood** [comment]
I just updated the wiki example on this:

http://wiki.ros.org/action/diff/xacro?action=diff&rev1=52&rev2=53

For groovy and hydro you should use the `find_package(...)` macro to get `xacro` included. For fuerte, we aren't supporting it anymore, so I would recommend updating to a newer ROS distribution where this is probably fixed up.

I am going to close this for now.
