### ISSUE TITLE
xacro:macro name

### ISSUE THREAD

**Issue by servetcoskun** [ros/xacro#133]
I think the above is broken again. In the kinetic-dev branch I'm getting the error:

`unknown macro name: xacro:base`

(This is after running the fix script) The xacro file it looks like this:
`<xacro:macro name>`
`...`
`</xacro:macro>`

Just needs a 'replace' after line 499 in [**init**.py](https://github.com/ros/xacro/blob/kinetic-devel/src/xacro/__init__.py)??

Or maybe I just messed up my xacro file..

**Comment by rhaschke** [comment]
Could you send your xacro file before and after auto-fixing?

**Comment by servetcoskun** [comment]
basically [seven_dof_arm.xacro](https://github.com/qboticslabs/mastering_ros/blob/master/chapter_2_codes/mastering_ros_robot_description_pkg/urdf/seven_dof_arm.xacro) I've changed the original such that my only remaining error is `unknown macro name: xacro:base`
`when processing file: seven_dof_arm.xacro`

**Comment by rhaschke** [comment]
I would consider this a bug in your xacro file. The macros 

```
  <xacro:base name="base"/>
  <xacro:arm parent="base"/>
  <xacro:gripper parent="tool"/>
```

are never defined, only used. 
With old xacro, they show up literally in the final urdf, which I consider a bug too.

**Comment by servetcoskun** [comment]
You are right, everything runs perfectly now. I will notify the repo owner asap, thanks for the help and sorry about the false alarm :)

**Comment by pastoradrianv92** [comment]
> You are right, everything runs perfectly now. I will notify the repo owner asap, thanks for the help and sorry about the false alarm :)

HI THERE! PLEASE SHOW ME HOW DID YOU FIX IT, How did you declare? how did you change the seven_dof_arm.xacro?

**Comment by wonggong** [comment]
> > You are right, everything runs perfectly now. I will notify the repo owner asap, thanks for the help and sorry about the false alarm :)
> 
> HI THERE! PLEASE SHOW ME HOW DID YOU FIX IT, How did you declare? how did you change the seven_dof_arm.xacro?

delete 
 <xacro:base name="base"/>
  <xacro:arm parent="base"/>
  <xacro:gripper parent="tool"/>
