### ISSUE TITLE
New release into Hydro?

### ISSUE THREAD

**Issue by piyushk** [ros/xacro#14]
@jonbinney Could you release a new version of xacro into Hydro. It would be nice to merge in #8 and #9 into the system release before beta ends.

**Comment by jonbinney** [comment]
Done: https://github.com/ros/rosdistro/pull/1645

**Comment by piyushk** [comment]
Awesome. I have documented the `<include>` tag deprecation from #9 at http://www.ros.org/wiki/hydro/Migration#Xacro
