### ISSUE TITLE
rosrun xacro xacro.py or rosrun xacro xacro fails with import error

### ISSUE THREAD

**Issue by AadityaRavindran** [ros/xacro#153]
Running on ROS Indigo on Raspberry Pi3 with Jessie. (This issue does not arise on Ubuntu 14.04 running ROS Indigo)

$ rosrun xacro xacro
Traceback (most recent call last):
  File "/home/username/catkin_ws/src/xacro-indigo-devel/scripts/xacro", line 53, in <module>
    import xacro
ImportError: No module named xacro

**Comment by rhaschke** [comment]
Have you correctly sourced your ROS workspace? `xacro` should be somewhere in the `PYTHONPATH`.

**Comment by rhaschke** [comment]
Closing due to missing feedback
