### ISSUE TITLE
xacro problem cannot load the parameter  returned with code  2

### ISSUE THREAD

**Issue by Avinash439** [ros/xacro#155]
![screenshot from 2017-08-03 16-35-34](https://user-images.githubusercontent.com/22390134/28927084-de6fb978-7869-11e7-988c-a9bb6180e7d6.png)
![screenshot from 2017-08-03 16-29-50](https://user-images.githubusercontent.com/22390134/28926744-fef9764e-7868-11e7-8b22-68d86ea9c676.png)

**Comment by guihomework** [comment]
Seems you miss the package ```fanuc_resources``` which is available here http://wiki.ros.org/fanuc or https://github.com/ros-industrial/fanuc
Adding it should solve your problem (worked for me)
I don't think this is a xacro issue.

**Comment by rhaschke** [comment]
@Avinash439 Can this issue be closed?

**Comment by Avinash439** [comment]
yes



Best Regards,

Narayana Poorna Naga Avinash
Research Masters Student
Computer Vision and Robotics
Erasmus - VIBOT
University of Burgundy
Le Creusot France
+33 - 07 <+33%207%2051%2001%2017%2051>53834175
