### ISSUE TITLE
local variable 'target_table' referenced before assignment

### ISSUE THREAD

**Issue by mintar** [ros/xacro#156]
When running xacro with an incorrectly set `scope` attribute, a local variable is referenced before assignment.

### Steps to reproduce

**minimal_example.urdf.xacro:**

```xml
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="math_pi" value="3.1415926535897931" scope="parent" />
</robot>
```

```
$ xacro --inorder minimal_example.urdf.xacro   
math_pi: no parent scope at global scope 
local variable 'target_table' referenced before assignment
UnboundLocalError("local variable 'target_table' referenced before assignment",)
when processing file: minimal_example.urdf.xacro
```

### relevant lines

https://github.com/ros/xacro/blob/b786d85d6b82f25a77b5547168a0b085448dd7e4/src/xacro/__init__.py#L546-L562

**Comment by rhaschke** [comment]
@mintar Could you please close this issue if it is solved with #157.
