### ISSUE TITLE
New release for lunar

### ISSUE THREAD

**Issue by kartikmohta** [ros/xacro#175]
There have been a lot of fixes for Python 3 support on the lunar-devel branch which would be good to have in the released version. Can we have a new release for lunar which include these changes?

**Comment by rhaschke** [comment]
@codebot @wjwwood 
Dear Morgan, are you still actively maintaining the xacro package?
We haven't seen new release for kinetic and lunar since a year now.

**Comment by rhaschke** [comment]
I released into both, `kinetic` and `lunar`.
