### ISSUE TITLE
Xacro Properties within Xacro Macros

### ISSUE THREAD

**Issue by rkeatin3** [ros/xacro#177]
Was support for creating properties within macros added in Jade?

The [ROS wiki for xacro](http://wiki.ros.org/xacro) states that properties cannot be instantiated within a macro, but I recently switched from Jade to Indigo, and now my xacro files (which _do_ use properties inside macros) are breaking. Should I update that page?

Secondly, would cherry-picking that behavior onto Indigo be possible? I would be happy to do the legwork myself if so.

**Comment by rhaschke** [comment]
I'm not quite sure about what you mean by "instantiated".
The major change introduced between Indigo and Jade is [`inorder` processing](http://wiki.ros.org/xacro#Processing_Order). Add that time we decided to not apply these changes to the Indigo branch. However, the Jade sources are also available within Indigo as a separate source folder `xacro_jade`, which is choosen as soon as you provide the `--inorder` option.
If you want to backport missing commits to this source folder, you are cordially invited.
