### ISSUE TITLE
Wiki page example it not working - if statement

### ISSUE THREAD

**Issue by JaFeKl** [ros/xacro#189]
Hello guys,

i tried to run the following example from your wiki page:

`<xacro:property name="allowed" value="[1,2,3]"/>
<xacro:if value="${1 in allowed}"/>`

however, it's not possible to be compile it like this:

`coercing to Unicode: need string or buffer, int found 
when evaluating expression '1 in allowed'`

so in order to make it a string instead of an integer, one has to add ' ' to make it work fine:

`<xacro:property name="allowed" value="[1,2,3]"/>
<xacro:if value="${'1' in allowed}"/>`

**Comment by rhaschke** [comment]
Thanks for this hint. Actually the one should be interpreted as an integer. The issue comes from the list not being correctly evaluated. The wiki referenced the wrong syntax. The list needs to be defined with evaluation `${...}` as follows:
`<xacro:property name="allowed" value="${[1,2,3]}"/>`
