### ISSUE TITLE
Feature request: '#pragma once' equivalent

### ISSUE THREAD

**Issue by JulianAssmann** [ros/xacro#191]
Often one wants to have one xacro file defining all materials/macros/whatever and include that file in multiple robot component files. Later, you want to combine these components in another file (e. g. 'my_robot.xacro'), that also needs those definitions and therefore includes the components as well as the materials/macros/whatever file. However if you do this, you get errors like

material 'Black' is not unique.

I presume that this is due to indirect multiple inclusions of the materials/macros/whatever files.

It would be nice, if the xacro converter detects these multiple includes and prevents copying the same file content twice, just like the #pragma once statement in C++.

See https://answers.ros.org/question/304797/pragma-once-equivalent-for-urdfxacro-files/ for examples.

**Comment by rhaschke** [comment]
As stated in [ros-answers](https://answers.ros.org/question/304797/pragma-once-equivalent-for-urdfxacro-files/#), one option to achieve this feature is using xacro conditionals:

```
<xacro:property name="guard" default="true"/>
<xacro:if value="${guard'}">
  <xacro:property name="guard" value="false"/>
  ...
</xacro:if>
```

In contrast to C++, where includes only occur on the top-level of files, in `xacro` includes can occur at any level of the XML hierarchy. I think, having a global `#once flag` would not be appropriate, as you probably want to allow inclusion in more deeply nested levels nevertheless.

Hence, I suggest to more cleanly modularize your files as suggest on ROS answers as well, or use the proposed workaround. If you come up with a PR, that considers my concerns, I'll be happy to consider it.

**Comment by rhaschke** [comment]
@JulianAssmann Can we close this issue?

**Comment by JulianAssmann** [comment]
@rhaschke Sure, sorry.

**Comment by firesurfer** [comment]
Sorry to comment on such an old issue, but does the supposed include guard workaround still work with https://github.com/ros/xacro/pull/373 being merged ? 

I run into the issue that the gazebo ros2control plugin may only be loaded once and I would like to put the instantiation  into a macro which makes sure that the plugin is loaded only once. 

(I acknowledge that the argument: structure the xacro in a different way still applies, but think of a complex system with separate sub-components which can also be used separately  - would be nice to make sure that the gazebo plugin is only loaded once) 

EDIT:

Tagging @rhaschke

**Comment by rhaschke** [comment]
The conditional solution stated [above](https://github.com/ros/xacro/issues/191#issuecomment-427333003) should still work. #373 is just related to the resolution of macro arguments, not properties.
Did you run into an actual issue?

**Comment by firesurfer** [comment]
I think I got that mixed up in my head. I implemented an include guard as described above and it seems to work fine. 
Thanks for your quick response
