### ISSUE TITLE
Creation of new banch as ros2-devel

### ISSUE THREAD

**Issue by vandanamandlik** [ros/xacro#196]
Hi,

Could you please create new branch as "ros2-devel" so that it will help to make pull request ?

Thanks,
Vandana

**Comment by rhaschke** [comment]
@vandanamandlik Please be a litte bit more patient before spamming other channels (discourse) with the same request. I just created the branch, but I won't have time to look into the details of #194 before Nov, 12th.

**Comment by vandanamandlik** [comment]
@rhaschke Thanks for creating branch.
