### ISSUE TITLE
CMake example on wiki is out of date

### ISSUE THREAD

**Issue by mikepurvis** [ros/xacro#20]
Clearly referencing a rosbuild workflow: http://wiki.ros.org/xacro#Building_from_CMakeLists.txt

There also needs to be attention drawn to the fact that with the catkin inversion, your workspace (and thus rospack) are not available at build time. This means no using $(find package) in your `<xacro:include>` tags if you intend to run the xacro at build time (at least on the buildfarm, anyway).

The workaround is to determine the path of the included file using [catkin-generated CMake trickery](http://answers.ros.org/question/104916/catkin_find-functionality-at-build-time/?answer=104936#post-id-104936), and then smuggle that into the xacro on the commandline for use as an `$(arg)`.

**Comment by wjwwood** [comment]
I updated the wiki page's CMake example (http://wiki.ros.org/action/diff/xacro?action=diff&rev1=52&rev2=53), but I did not modify it to say anything about finding resources from other packages at build time. Do you have an example of how that is done?  If you have one you know of, maybe I could use that to come up with an example for the wiki.

**Comment by mikepurvis** [comment]
I don't know of anyone doing this, but I'll be figuring it out shortly as part of some planned cleanup for robot_upstart's indigo release (to use xacro and otherwise be more conventional). If you're okay to leave the ticket open, I'll post back with a concrete example when I have one.

**Comment by wjwwood** [comment]
Sounds good, thanks.

**Comment by mikepurvis** [comment]
I did end up doing some more experimenting, and I the issue with $(find) was actually resolved here: https://github.com/ros/ros_comm/pull/233
