### ISSUE TITLE
Substitution arg for $(find pkg)

### ISSUE THREAD

**Issue by Levaru** [ros/xacro#225]
Hi, I'm currently at a roadblock with this issue. Is there a way to dynamically find directory paths for packages according to xacro args that i pass into the file via roslaunch? Maybe something like the eval command from roslaunch?

This works in a launch file:

```
<arg name="robot_name" default="kr60" />
<arg name="robot_path" default="$(eval find( arg('robot_name')+'_description'))" />

<!-- Load urdf description -->
<param name="robot_description" command="$(find xacro)/xacro '$(arg robot_path)/urdf/$(arg robot_name).urdf.xacro'"/>
```

But the same thing doesn't work in a xacro file:
```
<xacro:arg name="robot_name" default="kr60" />
<xacro:arg name="robot_path" default="$(eval find( arg('robot_name')+'_description'))" />

<!-- Load description modules -->
<xacro:include filename="$(arg robot_path)/urdf/$(arg robot_name).xacro" />
```

Is eval only available for roslaunch? Would it be possible to also include it in xacro?

**Comment by rhaschke** [comment]
No, we don't have `$(eval ...)` in `xacro`. But you can use a property within `$(find)`:
```xml
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/xacro" name="robot" xacro:targetNamespace="http://www.ros.org">
	<xacro:property name="robot_name" value="panda" />
	$(find ${robot_name}_moveit_config)
</robot>
```

**Comment by martinandrovich** [comment]
@rhaschke Is it possible to nest `$(find)` and `$(arg)` without the definition of a `<xacro:property />`? Something like:
```
...value="$(find $arg('robot_name'))" ...
```

**Comment by guihomework** [comment]
Hi, 

is it a problem to have the intermediate property being defined through the arg ?

```
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/xacro" name="robot" xacro:targetNamespace="http://www.ros.org">

<xacro:arg name="robot_name" default="kr60" />
<xacro:property name="robot_name" value="$(arg robot_name)" />
<xacro:arg name="robot_path" default="$(find ${robot_name}_description)" />

<!-- Load description modules -->
<xacro:include filename="$(arg robot_path)/urdf/$(arg robot_name).xacro" />
</robot>
```

**Comment by martinandrovich** [comment]
@guihomework No, not a problem per se; just one extra line of code. It's more of a curiosity whether it is possible to do so without the intermediate property.

**Comment by rhaschke** [comment]
No, nested arguments are not supported.
