### ISSUE TITLE
Example code for <xacro:element> and <xacro:attribute>

### ISSUE THREAD

**Issue by Levaru** [ros/xacro#226]
I'm confused what these two tags are used for. What is their benefit? What is their difference? 

The official [wiki](http://wiki.ros.org/xacro#Elements_and_Attributes) only has a syntax example:
```
<xacro:element xacro:name="${element_name}" [other attributes]>
 [content]
</xacro:element>
<xacro:attribute name="${attribute_name}" value="${attribute_value}"/>
```

**Comment by rhaschke** [comment]
Please have a look here: https://github.com/ros/xacro/issues/224#issuecomment-541589810
- `xacro:element` inserts a new element (with a dynamic element tag).
- `xacro:attribute` inserts a new attribute into the current element tag (with a dynamic attribute name)

If you think, the wiki should be augmented, please do so.
