### ISSUE TITLE
Dynamic macros

### ISSUE THREAD

**Issue by Levaru** [ros/xacro#227]
Is it possible to call macros dynamically? 

Example:
```
<xacro:macro name="example" >
[macro code]
</xacro:macro>

<xacro:dynamic_macro name="example" />
```

or maybe like this?

`<xacro:${example}  />`

**Comment by rhaschke** [comment]
It is: https://github.com/ros/xacro/blob/melodic-devel/test/test_xacro.py#L301-L309

**Comment by Timple** [comment]
The link is wrong now. But for the record:

```xml
 <xacro:call macro="example" />
```
