### ISSUE TITLE
[ros2] ':' or '\t' in comments lead to error

### ISSUE THREAD

**Issue by mganglb** [ros/xacro#231]
Hello, 

i would look for an ez way to delete all comments  out of the processed doc.

Reason:  ':' or '\t' in comments lead to errors when used in  a LaunchDescription.

i would do it myself, but i have literally no experience with xml.dom.minidom. If noone is solving the problem, i would have time for it at the end of february.

approach:
  doc.delete_comments()

regards mgangl

**Comment by rhaschke** [comment]
Shouldn't this be done at the side of LaunchDescription instead of xacro?
Usually, we _want_ to keep comments.

**Comment by mganglb** [comment]
hmm, have not thought of that so far. I will create an issue in ros_launch in the next days.
