### ISSUE TITLE
`python`: No such file or directory

### ISSUE THREAD

**Issue by DLu** [ros/xacro#237]
Via https://github.com/ros/urdf_sim_tutorial/issues/7

With Ubuntu 20.04/noetic, @qboticslabs is having trouble with getting xacro to run Python code. This may go further upstream than `xacro`, but I'm starting here. 

```
$ rosrun xacro xacro.py
/usr/bin/env: ‘python’: No such file or directory
```

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-noetic-call-for-testing/14203/5

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-noetic-call-for-testing/14203/1

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-noetic-ninjemys-release/14262/14
