### ISSUE TITLE
Release into Foxy

### ISSUE THREAD

**Issue by emersonknapp** [ros/xacro#241]
Bloom into ROS2 Foxy

xacro is bloomed into eloquent on the `dashing-devel` branch https://github.com/ros/rosdistro/blob/master/eloquent/distribution.yaml#L3398 - perhaps there should be a `ros2` branch?

**Comment by rhaschke** [comment]
Done: https://github.com/ros/rosdistro/pull/25383

**Comment by emersonknapp** [comment]
Thanks!
