### ISSUE TITLE
a error or bug about multi-gazebo_ros_control.so in robot

### ISSUE THREAD

**Issue by Sunchanghao** [ros/xacro#242]
In my car.xacro, it include a gimbal.xacro and a manipulator.xacro 
in gimbal.xacro i have:

```
   <gazebo>
         <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
              <robotNamespace>/dji_gimbal</robotNamespace>
          </plugin>
    </gazebo>
```

at the same time, in manipulator.xacro, there also has:

```
     <gazebo>
            <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
                <robotNamespace>/arm</robotNamespace>
            </plugin>
       </gazebo>
```

There are no problems so far, I can move manipulator in rviz by using MotionPlanning.
but, when I use a python program to control the manipulator, there something wrong:
I can see that the manipulator do a repetitive exercise between initial state and specify location.

and then, I delete the ros_control.so in gimbal.xacro and restart the program, here, the manipulator can move to specified position and keep still.

so ｗhat's the problem, why can I use the program normally after I delete one gazebo_ros_control.so in gimbal.xacro?

thank you!

**Comment by rhaschke** [comment]
This issue is not related to xacro. I'm sure you will observe the same behavior with the generated URDF. Please address your questions to ROS answers and provide more details / allow people to reproduce your problem.
