### ISSUE TITLE
Melodic 1.13.10 release

### ISSUE THREAD

**Issue by Doomerdinger** [ros/xacro#269]
@rhaschke could you kick off the release process for the 1.13.10 version on melodic?
I've tried to do it myself but I've not used bloom before, and after reading through the tutorial and tinkering a bit I'm not entirely sure exactly how with a pre-existing repository like this.

**Comment by Doomerdinger** [comment]
Actually it may be better to wait until [issue 270](https://github.com/ros/xacro/issues/270) gets addressed, assuming it is actually a bug

**Comment by rhaschke** [comment]
Uups. I missed to release that one... Fixed: https://github.com/ros/rosdistro/pull/28888
