### ISSUE TITLE
xacro-extras.cmake broken in Hydro

### ISSUE THREAD

**Issue by cottsay** [ros/xacro#27]
`xacro-extras.cmake` references the Xacro executable like so:

``` cmake
set(_xacro_py
  /opt/ros/hydro/lib/xacro/scripts/xacro.py
)
```

This file is not part of Xacro. I just checked the debian for `raring` and the misconfiguration was there. The fact that this has been wrong for so long leads me to believe that I'm missing something.

If I'm right, either the file should be installed, or (more likely) the path should be updated.

**Comment by wjwwood** [comment]
@codebot9000

**Comment by cottsay** [comment]
I think this was fixed by https://github.com/ros/xacro/commit/68453f8921785ccf54a5b112dc4a69568d219f86 but never released.

**Comment by mikepurvis** [comment]
Yes, new Hydro release please!

**Comment by mikepurvis** [comment]
@codebot9000 This ticket can be closed, I believe.
