### ISSUE TITLE
[Error] : could n't find xacro.py

### ISSUE THREAD

**Issue by rahul0805** [ros/xacro#273]
Couldn't find xacro.py

When I run the command:  **rosrun xacro xacro.py** 

I got this error  
  
-----
[rosrun] Couldn't find executable named xacro.py below /opt/ros/noetic/share/xacro
----

I'm not sure how to fix this. Please help

**Comment by rhaschke** [comment]
Read the docs, please: http://wiki.ros.org/noetic/Migration#Use_xacro_instead_of_xacro.py
