### ISSUE TITLE
xacro reads the content in comment and fail to load xacro

### ISSUE THREAD

**Issue by lianghongzhuo** [ros/xacro#311]
This happens in both melodic and noetic.
When loading a xacro file with comment,  it did not ignore the comment and failed to load the xacro.
To reproduce, just add an invalid comment in xacro file (`<!-- <material name="${color}" /> -->`):
```
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" /> 
      <geometry>
        <mesh filename="package:///meshes.stl" scale="1 1 1"/>
      </geometry>
      <!-- <material name="${color}" /> -->
    </visual>
```

**Comment by rhaschke** [comment]
Looks like you are using an old version. Please update to 1.14.13 (Noetic) / 1.13.17 (Melodic).
See #300 and #310 for details.

**Comment by lianghongzhuo** [comment]
my melodic is still 1.13.15. seems ros did not update yet

**Comment by lianghongzhuo** [comment]
noetic is now up to date (1.14.13) and should be fine now.
