### ISSUE TITLE
resource not found error

### ISSUE THREAD

**Issue by smileyenot983** [ros/xacro#313]
After recent commits i have an error with the process of converting xacro to urdf 

After i run this:
`rosrun xacro xacro robot.xacro DEBUG:=True SIMPLE_COLLISION:=True > robot_generated.urdf`
I get an error with following output:
resource not found: a1_gazebo
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/ramil/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share
when processing file: robot.xacro

**Comment by rhaschke** [comment]
You are looking for a package name `a1_gazebo`. Check your files for `$(find a1_gazebo)`!
If you find this in some comments, you migth run into #311.

**Comment by smileyenot983** [comment]
The thing is that we have 2 same repos on different PCs(one with the newest ROS and one with ROS installed earlier without recent updates), on PCs with newest ROS we got this problem, but everything works well on PCs with ROS without recent updates

**Comment by rhaschke** [comment]
As said before, you might run into #311. Please provide your ROS distro version as well as your xacro version for more help.

**Comment by smileyenot983** [comment]
I have tried to find the place in xacro where it searches for a1_gazebo, i was commented, after deleting this comment everything works well.

ros version is:
 * /rosdistro: melodic
 * /rosversion: 1.14.12

don't know how to check xacro version

**Comment by rhaschke** [comment]
I have cut a new release for Melodic recently, which is not yet synced. Consider using the debian packages from the [ROS `testing` repo](http://wiki.ros.org/TestingRepository) or build from source.

**Comment by smileyenot983** [comment]
Thanks, will wait for ros updates
