### ISSUE TITLE
How to install and use xacro on ros humble hawksbill?

### ISSUE THREAD

**Issue by mohanksriram** [ros/xacro#319]
I tried `sudo apt install ros-humble-xacro` to install.
And then ran `ros2 run xacro xacro --inorder -o hand.urdf hand.xacro`

But I get the error `Package 'xacro' not found`

**Comment by rhaschke** [comment]
Is this related to https://github.com/ros/xacro/issues/302, i.e. are you running on Windows?
Did you source your ROS environment after installing xacro?
Is there a folder /opt/ros/humble/share/xacro?

**Comment by mohanksriram** [comment]
No, I'm running on ubuntu 22.04
Yes, I did: `. ~/ros2_humble/install/local_setup.bash`
Yes there is a folder:  /opt/ros/humble/share/xacro

**Comment by rhaschke** [comment]
Does it work when you source directly from /opt/ros ?

**Comment by mohanksriram** [comment]
Thanks!
Directly sourcing: `. /opt/ros/humble/local_setup.sh` worked.
Now, I'm able to ros2 run xacro.

**Comment by rhaschke** [comment]
This means that screwed your local workspace.
