### ISSUE TITLE
xacro file command cannot used in windows 10 with ros moveit package

### ISSUE THREAD

**Issue by Jason-Lee0** [ros/xacro#327]
Hello , 

I tried to use ROS moveit package on Windows 10 System with ROS Noeitic .
I followed the tutortial of moveit installation which website is 
https://ms-iot.github.io/ROSOnWindows/Moveit/moveit_tutorials.html . 

After this tutorial, I ran the command 
**roslaunch panda_moveit_config demo.launch rviz_tutorial:=true**

then it showed the error below. 

![image](https://github.com/ros/xacro/assets/56862464/8c3dab99-2889-45bb-90d9-9e7b38f95841)

it said **name 'python' not defined.** 
I have tried to  build xacro from source, but it didn't work.

Did anyone meet this problem before ?  Or What could I try to fix this problem ?
Thanks for your watching.  

Have a nice day !!
 
 ----------------------
System OS : Windows 10
ROS version : ROS Noetic

**Comment by rhaschke** [comment]
This isn't a problem with xacro, but a fundamental issue in your ROS/python installation.
Instead of using ROS natively in Windows as suggested in the given link, I always recommend using a WSL-based installation: https://github.com/rhaschke/lecture/wiki/WSL-install
