### ISSUE TITLE
Feature request: abs() function in ${.} expressions

### ISSUE THREAD

**Issue by mfbehrens** [ros/xacro#332]
While implementing some too complicated calculations in xacro I noticed that python's `abs` is not usable in xacro.
Sorry if it is available, but I could not find it in the `python` nor in the `math` namespace, and I could not find it in any documentation.

**Comment by rhaschke** [comment]
I can reproduce the missing `abs` function. However, I don't understand why it is missing. Here is a simple alternative: Use `fabs`:
```xml
<bar function="${fabs(-3)}"/>
```

**Comment by mfbehrens** [comment]
Thank you! That would fix it.
I created a pull request to add support for abs. If you want to merge it, do so, otherwise just close it.

**Comment by rhaschke** [comment]
Fixed via https://github.com/ros/xacro/commit/d9b66790de780fb125b5b3d7fbae9b2139559ca0
