### ISSUE TITLE
setup.py install is deprecated. Use build and pip and other standards-based tools

### ISSUE THREAD

**Issue by felixf4xu** [ros/xacro#334]
Hi,

When I build this repo (ros2 branch) by `colcon` (ros2 humble on Ubuntu 22, python 3.10.12), I had this error:

```sh
--- stderr: xacro
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
```

**Comment by felixf4xu** [comment]
maybe related: https://github.com/ros/xacro/issues/328

**Comment by rhaschke** [comment]
setup.py is still the standard way of installing python packages in ROS. I think they are aware of the deprecation issue...
