### ISSUE TITLE
Unable to resolve namespace within property block and not able to pass a block by a macro to macro with insert_block

### ISSUE THREAD

**Issue by naimen** [ros/xacro#337]
Hi I've been playing around with insert_block and property blocks, and discovered that it can't evaluate the following example, where it throws error of 
``` 
unknown macro name: xacro:CH.bar
when instantiating macro: insert (child.xml)
in file: parent.xml

``` 

parent.xml
```  
    <xacro:include filename="child.xml" ns="CH"/>

    <xacro:property name="A_block" scope="global" lazy_eval="false">
        <xacro:CH.barA="-1" B="2"/>
    </xacro:property>

    <xacro:CH.insert/>

    <xacro:CH.insert_2>
        <foo>
            <xacro:CH.barA="-1" B="2"/>
        </foo>
    </xacro:CH.insert_2>
``` 

child.xml
```  
    <xacro:macro name="bar" params="A B">
        <bar data="${A} 0 1 ${B}"/>
        <bar data="${B} 1 0 ${A}"/>
    </xacro:macro>

    <xacro:macro name="insert">
        <foo>
            <xacro:insert_block name="A_block"/>
        </foo>
    </xacro:macro>

    <xacro:macro name="insert_2" params="**foo">
        <foo>
            <xacro:insert_block name="foo"/>
        </foo>
    </xacro:macro>   
```

Any idea of how to handle this?

**Comment by rhaschke** [comment]
You must not use the namespace `CH` when referring to the macro `bar` within `child.xml`, because the macro is already executing within that namespace:
```xml
<parent xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="child.xml" ns="CH"/>

	<xacro:property name="A_block" scope="global" lazy_eval="false">
		<xacro:bar A="-1" B="2"/>
	</xacro:property>

	<xacro:CH.insert/>

	<xacro:CH.insert_2>
		<foo>
			<xacro:bar A="-1" B="2"/>
		</foo>
	</xacro:CH.insert_2>
</parent>
```

**Comment by naimen** [comment]
> You must not use the namespace `CH` when referring to the macro `bar` within `child.xml`, because the macro is already executing within that namespace:
> 
> ```
> <parent xmlns:xacro="http://ros.org/wiki/xacro">
> 	<xacro:include filename="child.xml" ns="CH"/>
> 
> 	<xacro:property name="A_block" scope="global" lazy_eval="false">
> 		<xacro:bar A="-1" B="2"/>
> 	</xacro:property>
> 
> 	<xacro:CH.insert/>
> 
> 	<xacro:CH.insert_2>
> 		<foo>
> 			<xacro:bar A="-1" B="2"/>
> 		</foo>
> 	</xacro:CH.insert_2>
> </parent>
> ```

Thanks for the reply, so when I'm calling the macro I will be in scope of the called macro(or file)? Because if i move the macro `bar` to the `parent.xml`, then xacro fails with 

```
unknown macro name: xacro:bar
when instantiating macro: insert (child.xml)
in file: parent.xml
```

**Comment by rhaschke** [comment]
Sure. The block is interpreted within the context of the macro. If the macro is in the namespace, you don't need to add the namespace again. If the macro is moved out from the namespace, you need to specify the namespace explicitly.

**Comment by naimen** [comment]
> Sure. The block is interpreted within the context of the macro. If the macro is in the namespace, you don't need to add the namespace again. If the macro is moved out from the namespace, you need to specify the namespace explicitly.

If my macro `bar` is inside `parent`, then when i'm executing the macro `child.insert` where it points to a property block defined in `parent` that calls `bar` without lazy_eval, I will be in the context of `insert` within `child` and performes the evaulation of property block where i calls `bar` from that context? 

So there's no way for me to pass block created by a macro from a context into a another macro in another context?

**Comment by rhaschke** [comment]
> So there's no way for me to pass block created by a macro from a context into a another macro in another context?

No, I'm afraid that's not possible.

**Comment by naimen** [comment]
> > So there's no way for me to pass block created by a macro from a context into a another macro in another context?
> 
> No, I'm afraid that's not possible.

Alright, is there any kind of workaround for that then? 
What i want to achive is to use a macro to create a block, then pass that block to another macro

**Comment by rhaschke** [comment]
Correctly pass the namespace.

**Comment by naimen** [comment]
> Correctly pass the namespace.

You can pass namespace? :open_mouth: 
Do you have an example of pass `ns1` to a macro in `ns2` without explicity includ that `ns1` inside `ns2`?

**Comment by rhaschke** [comment]
As I wrote, you cannot cross-reference namespaces. Namespaces were introduced to distinguish two child-namespaces from within a common parent. They are not intended to access ns1 from within ns2.
