### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by cybaol** [ros/xacro#343]
OS: archlinux
ROS2 distribution: humble
Python Version: 3.12
Xacro Version: 2.0.11
error log: [pytest.xunit.log](https://github.com/ros/xacro/files/15322251/pytest.xunit.log)

**Comment by rhaschke** [comment]
All tests pass on Ubuntu 24.04 (ROS Rolling, python 3.12): https://github.com/ubi-agni/xacro/actions/runs/9097612778/job/25005822894
So, I'm afraid your python installation on archlinux is broken.

**Comment by cybaol** [comment]
But version `2.0.9` is OK on archlinux.
![Screenshot_select-area_20240515224952](https://github.com/ros/xacro/assets/48387783/c1896604-b619-412e-9bdd-5a1d9958508c)

Version `2.0.10` and `2.0.11` all test failed.

Test command: `ctest --output-on-failure`

**Comment by rhaschke** [comment]
I don't have an archlinux distro available to look into this. The error log points at custom yaml constructors not working:
https://github.com/ros/xacro/blob/88129b7c8e54b5fc8f8da632c35c19508d598976/xacro/__init__.py#L134-L135

Any help is welcome.

**Comment by cybaol** [comment]
The important thing I forgot was to set the `PYTHONPATH` environment variable before testing.
 So the test command should be: `PYTHONPATH="$PWD/ament_cmake_python/xacro:$PYTHONPATH" ctest --output-on-failure`.
 And then all tests passed.
 
 If the environment variable is not set, it will preferentially `import xacro` from OS (order version existing in Operating System).

**Comment by rhaschke** [comment]
So, I guess we can close this.
