### ISSUE TITLE
bug: default argument not followed in a certain case

### ISSUE THREAD

**Issue by TomCC7** [ros/xacro#346]
Hi, I found that in some cases the xacro parser won't follow the default argument. For example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="$(arg name)">

    <!-- robot name parameter -->
    <xacro:arg name="name" default="rizon"/>
    <xacro:property name="name" default="$(arg name)"/>


    <disable_collisions link1="${name}gripper_base_link" link2="${name}link7" reason="Adjacent"/>
    <disable_collisions link1="${name}gripper_base_link" link2="${name}flange" reason="Adjacent"/>
    <disable_collisions link1="${name}gripper_base_link" link2="${name}gripper_left_finger" reason="Adjacent"/>
    <disable_collisions link1="${name}gripper_base_link" link2="${name}gripper_right_finger" reason="Adjacent"/>

</robot>
```

Here I set the argument name to have default `rizon`, but it fails when I run `xacro` without specifying name directly. When I remove the argument in line
```xml
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="$(arg name)">
```
it works.

I think this is a bug because when I specify the name in cli it works fine.

**Comment by rhaschke** [comment]
Obviously, the argument cannot be used before its definition. When you define the arg on the cli it is defined from the very beginning. Otherwise, you need to wait for the `<xacro:arg>` definition before you can use it.
