### ISSUE TITLE
Inconsistent version metadata

### ISSUE THREAD

**Issue by jwnimmer-tri** [ros/xacro#349]
In 5aa788e the version number was updated in `package.xml` but not in `pyproject.toml`.

https://github.com/ros/xacro/blob/88129b7c8e54b5fc8f8da632c35c19508d598976/package.xml#L4

https://github.com/ros/xacro/blob/88129b7c8e54b5fc8f8da632c35c19508d598976/pyproject.toml#L6

(This is for the `ros2` branch.)

**Comment by rhaschke** [comment]
Thanks for pointing this out. Version is now determined from git (e956f945a31901773801dafe90f5aa4905b0f981).
